import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {strict as assert} from 'node:assert';
const state=JSON.parse(readFileSync('evidence/v03-finalized-state.json','utf8'));
assert.equal(state.address,'0x58E44E52fABfbFcF83759F8eB8296B81cc517E11');
assert.equal(state.state,'LATEST_FINAL');assert.equal(state.claims[0].status,'REFUTED');
assert.equal(state.claims[0].attempts,2);assert.equal(state.attempts.length,2);
const [invalid,valid]=state.attempts;
assert.equal(invalid.reason,'SOURCE_UNAVAILABLE');assert.equal(invalid.outcome,'REFUNDED');
assert.equal(invalid.challenger_credit_wei,'1000000000000000000');
assert.equal(valid.verdict,'COMPARABLE');assert.equal(valid.outcome,'REFUTED');assert.equal(valid.previous_attempt,invalid.id);
assert.equal(valid.challenger_credit_wei,'2000000000000000000');assert.notEqual(valid.challenger.toLowerCase(),invalid.challenger.toLowerCase());
const original=state.claims[0];assert.equal(createHash('sha256').update(original.evidence_snapshot).digest('hex'),original.evidence_sha256);
assert.equal(Buffer.byteLength(original.evidence_snapshot),original.evidence_bytes);
assert.equal(createHash('sha256').update(valid.evidence_snapshot).digest('hex'),valid.evidence_sha256);
assert.equal(Buffer.byteLength(valid.evidence_snapshot),valid.evidence_bytes);
for(const r of state.attempts)assert.equal(r.claim_commitment,original.commitment);
const a=state.accounting;assert.equal(BigInt(a.deposited_wei),BigInt(a.locked_wei)+BigInt(a.credit_wei)+BigInt(a.withdrawn_wei));
assert.equal(a.locked_wei,'0');assert.equal(a.credit_wei,'3000000000000000000');assert.equal(a.withdrawn_wei,'0');
console.log('Verified finalized invalid-then-legitimate challenge, evidence fingerprints and 3 GEN settlement credits. Withdrawal was blocked by automatic approval review; no v0.3 payout transfer is claimed.');
